{% set version = "0.5" %}

package:
  name: overpy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/overpy/overpy-{{ version }}.tar.gz
  sha256: 2fb711df0771cd904049d523b58a0b47675bd23baccce9b40ef8eb139deacb03

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python

test:
  imports:
    - overpy

about:
  home: https://github.com/DinoTools/python-overpy
  license: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Python Wrapper to access the OpenStreepMap Overpass API

extra:
  recipe-maintainers:
    - ocefpaf
