{% set name = "overpy" %}
{% set version = "0.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/overpy-{{ version }}.tar.gz
  sha256: 75fa462c445a3d8ade4dad84df6f150d273f45548639229316829a3a8c3e2190

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - pytest-runner
  run:
    - python >=3.6

test:
  imports:
    - overpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/DinoTools/python-overpy
  summary: Python Wrapper to access the OpenStreepMap Overpass API
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
