{% set name = "overpy" %}
{% set version = "0.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/overpy-{{ version }}.tar.gz
  sha256: f6df5073de0cc1f63aed6d2632140f98c3d91fa3a2e3bef1bcfaa6225500f364

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - pytest-runner
  run:
    - python >=3.6

test:
  imports:
    - overpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/DinoTools/python-overpy
  summary: Python Wrapper to access the OpenStreepMap Overpass API
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
